### ISSUE TITLE
Linux 用户要自行编译吗？

### ISSUE THREAD

**Issue by ghost** [Konano/Ingress-Field-Design#1]
Linux 无法运行 choose 等程序，是不是要自行编译？
如果需要，我可以提供编译后的二进制文件。

**Comment by Konano** [comment]
需要自行编译。
能的话可以提供下在 Linux 编译得到的二进制文件。

**Comment by ghost** [comment]
@Konano 我建议加上 CMake 编译支持，不然编译会比较麻烦。
当然你也可以用虚拟机装个 Linux 来编译。
