### ISSUE TITLE
运行系统要求是什么

### ISSUE THREAD

**Issue by talosu** [Konano/Ingress-Field-Design#2]
##### 1. archlinux 一下截图
![image](http://7xll3b.com1.z0.glb.clouddn.com/iScreenshot%20from%202017-12-06%2017-43-19.png)

##### 2.windows 7 32位
![image](http://7xll3b.com1.z0.glb.clouddn.com/iScreenshot%20from%202017-12-06%2017-40-37.png)

**Comment by Konano** [comment]
Linux 还需自行编译。
Window 版本的 exe 是 64 位系统环境。
